spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reaktor_booking_server?createDatabaseIfNotExist=true
    username: root
    password: toor
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
  file:
    name: /tmp/reaktor_booking_server.log
    max-size: 1MB
    max-history: 10
    total-size-cap: 10MB

server:
  port: 8082