package es.iesjandula.reaktor_booking_server.models;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Embeddable
public class TramoHorarioId implements Serializable
{
	/**
	 * AutoGenerated
	 */
	private static final long serialVersionUID = -86643101492426938L;

	@Column
<<<<<<< HEAD
	private String hora_inicio;

	@Column
	private String hora_fin;
=======
    private String horaInicio;

    @Column
    private String horaFin;
>>>>>>> 1395ab93cede9a5ae21626be8c2e993255544c31
}
